spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/gobread
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# spring.security.user.name=tqtoan
# spring.security.user.password=$2a$10$Az/v4a5RYvEwTF38MUvVJuJ0cl9me2Dnha/9cUG7xA4HJrh1nTBky


# #config view engine
# spring.mvc.view.prefix=/WEB-INF/view/
# spring.mvc.view.suffix=.jsp

#  chỉ định loại Connection Pool
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# Cấu hình pool 
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000


# Cấu hình upload file
#default = 1mb
spring.servlet.multipart.max-file-size=50MB
#default = 10mb 
spring.servlet.multipart.max-request-size=50MB

# config session
spring.session.store-type=jdbc
spring.session.timeout=30m
spring.session.jdbc.initialize-schema=always
# server.servlet.session.timeout
# spring.session.jdbc.table-name= SPRING_SESSION
